// 🏴‍☠️ El alma del ataque: Diccionario híbrido (Español + Contexto de Examen de Seguridad)
  export const DICCIONARIO: string[] = [
    // Conectores y artículos (con espacios a los lados para no hacer falsos positivos)
    ' de ',
    ' la ',
    ' el ',
    ' en ',
    ' y ',
    ' a ',
    ' los ',
    ' las ',
    ' un ',
    ' una ',
    ' con ',
    ' para ',
    ' es ',
    ' del ',

    ' a ',
    ' ante ',
    ' bajo ',
    ' con ',
    ' contra ',
    ' de ',
    ' desde ',
    ' en ',
    ' entre ',
    ' hacia ',
    ' hasta ',
    ' para ',
    ' por ',
    ' segun ',
    ' sin ',
    ' sobre ',
    ' tras ',

    // Preguntas de examen (se evalúan en minúsculas)
    'qué',
    'cual',
    'cuales',
    'cuáles',
    'define',
    'explica',
    'menciona',
    'describe',
    'como',
    'cómo',
    'por',
    'que',
    'porque',
    'cuándo',
    'dónde',
    'quién',
    'quienes',
    'cuánto',
    'cuánta',
    'cuántos',
    'cuántas',

    // Términos técnicos de infraestructura y seguridad informática
    'cifrado',
    'simetrico',
    'simétrico',
    'asimetrico',
    'asimétrico',
    'hash',
    'vulnerabilidad',
    'red',
    'protocolo',
    'paquetes',
    'seguridad',
    'criptografia',
    'criptografía',
    'clave',
    'publica',
    'pública',
    'privada',
    'ataque',
    'texto',
    'plano',
    'linux',
    'openssl',
    'router',
    'switch',
    'tcp',
    'ip',
    'modelo',
    'osi',
    'seguridad',
    'triangulo',
    'informacion',
    'confidencialidad',
    'disponibilidad',
    'integridad',
    'confiabilidad',
    'equipos',
    'comunicaciones',
    'amenaza',
    'amenazas',
    'vulnerabilidad',
    'vulnerabilidades',
    'esquema',
    'esquemas',
    'defensa',
    'enemigo',
    'motivo',
    'motivos',
    'ethical',
    'hacking',
    'monitoreo',
  ];
